# Spring Boot settings
spring:
  jpa:
    database: postgresql
    hibernate.ddl-auto: update
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}

# Telegram Bot settings
telegram:
  bot:
    mention:
      regex: (^[Бб]от([,!\.].*)?$)|(.*,\sбот[?!.]?$)
      cooldown:
        timeout_ms: 20000
        max_messages_in_timeout_allowed: 2
        duration_sec: 300

    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}