services:
  # Application
  back:
    image: doctordrue/sticker-bot
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/${APP_DB_NAME}
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5005:5005" # Java Remote debug
    depends_on:
      - db
    restart: always

  # Database
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    restart: always
    volumes:
      - pg_sharedcosts:/var/lib/postgresql/data
    ports:
      - "5432:5432" # For debug purpose

#  db_new:
#    image: postgres:alpine
#    environment:
#      POSTGRES_DB: ${APP_DB_NAME}
#      POSTGRES_USER:  ${APP_DB_USERNAME}
#      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
#    restart: always
#    volumes:
#      - database:/var/lib/postgresql/data
#    ports:
#      - "5432:5432" # For debug purpose

volumes:
  database:
  pg_sharedcosts: