name: Publish gradle release image
on:
  push:
    branches: [ main ]
  workflow_dispatch: 
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v3
        
    - name: Log in to the Container registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.1.5
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: bootBuildImage --
          
    - name: Publish on docker.io
      run: |
          docker push --all-tags ${{ env.IMAGE_NAME }}
